### ISSUE TITLE
R421B16 support

### ISSUE THREAD

**Issue by DarkPark** [Erriez/R421A08-rs485-8ch-relay-board#1]
Can you please add support of the very similar device R421B16?
Actually it is already almost working. I've set `NUM_RELAYS = 16` in `R421A08.py` and everything works as expected.

**Comment by Erriez** [comment]
Thanks for your feedback. This project was created when the `R421B16` board did not exists. The entire project consists of `R421B8`. I've included your comment in the README.md instead of renaming all files/functions/comments.

**Comment by cizekmilan** [comment]
I released my project for multiple R421B16, https://github.com/cizekmilan/rcpd-backend.
