### ISSUE TITLE
toggle_multi, toggle, _send_relay_command fails on R421A16

### ISSUE THREAD

**Issue by cizekmilan** [Erriez/R421A08-rs485-8ch-relay-board#2]
Hi, I have R421A16, I made copy of  R421A08.py -> R421A16.py and edited NUM_RELAYS variable to 16.
Commands are executed successfully, but often fail. What can be the cause?

`./getting_started.py
Getting started R421A16 relay board

Status all relays:
Relay 1: OFF
Relay 2: OFF
Relay 3: OFF
Relay 4: ON
Relay 5: OFF
Relay 6: ON
Relay 7: OFF
Relay 8: OFF
Relay 9: OFF
Relay 10: OFF
Relay 11: OFF
Relay 12: OFF
Relay 13: OFF
Relay 14: OFF
Relay 15: OFF
Relay 16: OFF
Turn relay 1 on
Turn relay 1 off
Toggle relay 8
Latch relays 6 on, all other relays off
Turn relay 4 on for 5 seconds, all other relays off
Turn relays 3, 7 and 8 on
Traceback (most recent call last):
  File "./getting_started.py", line 92, in <module>
    check(board.toggle_multi([3, 7, 8]))
  File "/5/relay_boards/R421A16.py", line 354, in toggle_multi
    retval = self.toggle(relay)
  File "/5/relay_boards/R421A16.py", line 295, in toggle
    return self._send_relay_command(relay, CMD_TOGGLE)
  File "/5/relay_boards/R421A16.py", line 186, in _send_relay_command
    rx_frame = self._modbus.receive(RX_LEN_CONTROL_COMMAND)
  File "/5/relay_modbus/modbus.py", line 316, in receive
    raise TransferException('RX error: Receive timeout')
relay_modbus.modbus.TransferException: RX error: Receive timeout

**Comment by Erriez** [comment]
Hi @cizekmilan, Someone else was able to change the number of relays from 8 to 16 as reported in issue #1. I'm not sure which code changes are needed because I don't have a board with 16 relays.

A receive timeout may occur when the serial connection does not work reliable. Can your board deliver sufficient power from the power supply? 
What happens when turning on one relay after each other instead of multiple at the same time?

**Comment by cizekmilan** [comment]
Hi,

my setup is RPI2 and USB to RS485 converter. I tried with external power supply (max. 2.5A).
I using twisted pair for RS485 (1m), I also tried add 120ohm termination of RS485 bus.

> What happens when turning on one relay after each other instead of multiple at the same time?
Test
on->off->on->off ... also often fails.

I tried add time.sleep to for loops, but it does not solve the problem.
I can provide SSH for bettere debugging.

**Comment by Erriez** [comment]
You can try to increase the serial timeout in `relay_modbus/modbus.py` from `self._ser.timeout = 0.1` to `self._ser.timeout =1.0`, but I'm not sure if this will help.

I suggest to test the low level RS485 USB interface first. For example by reading the status and print the serial transmit/receive output by enabling `verbose=True`. There can be a baudrate deviation in the RS485 adapter.

**Comment by cizekmilan** [comment]
I changed modpus.py FRAME_DELAY = 0.010 to value 0.025.
I have repeatedly tested the value by gradually increasing it, now it works reliably. The problem seems to be solved. I will test even more. Thank you!

**Comment by Erriez** [comment]
Good to hear that you found a solution. I've applied your fix in master. Thanks!
